# These are supported funding model platforms

github: https://github.com/CrimsonX77/
patreon: https://www.patreon.com/cw/CrimsonDragonX7
ko_fi: https://ko-fi.com/crimsondragonx7
custom: https://www.youtube.com/@CrimsonDragonX7, https://suno.com/@redstrucksolo550, https://www.facebook.com/crimson.valentine.1, https://discord.gg/XT2XBarW
